const prettyKey = (k) => (k || '').replace(/_/g, ' ').replace(/\b\w/g, ch => ch.toUpperCase());

function renderValue(v) {
  if (v === null || v === undefined || v === '') return '—';
  if (typeof v === 'object') return JSON.stringify(v);
  return String(v);
}

export default function AnalyzeResultModal({ result, onClose }) {
  const extracted = result?.extracted || {};
  const entries = Object.entries(extracted);

  return (
    <div className="modal-overlay">
      <div className="modal w-[560px] max-h-[90vh] overflow-y-auto px-8 py-7">
        <div className="mb-1.5 flex items-center justify-between">
          <h2 className="text-lg font-bold text-navy">✨ AI Analysis</h2>
          <button onClick={onClose} className="text-2xl text-gray-400">×</button>
        </div>
        <div className="mb-5 text-[11px] text-gray-400">Generated by {result?.model || 'Claude'} · review before relying on extracted values</div>

        <div className="field-section">SUMMARY</div>
        <div className="mb-5 text-sm leading-relaxed text-ink">{result?.summary || '—'}</div>

        {result?.suggested_category && (
          <div className="mb-5">
            <span className="field-section mr-2.5 inline">SUGGESTED CATEGORY</span>
            <span className="rounded-full bg-purple-600/10 px-3 py-1 text-xs font-bold text-purple-600">
              {prettyKey(result.suggested_category)}
            </span>
          </div>
        )}

        <div className="field-section">EXTRACTED FIELDS</div>
        {entries.length === 0 ? (
          <div className="text-[13px] text-gray-400">No fields extracted.</div>
        ) : (
          <div className="overflow-hidden rounded-lg border border-gray-100">
            {entries.map(([k, v], i) => (
              <div key={k} className={`flex ${i < entries.length - 1 ? 'border-b border-gray-100' : ''}`}>
                <div className="w-[180px] bg-gray-50 px-3 py-2.5 text-xs font-semibold text-gray-600">{prettyKey(k)}</div>
                <div className="flex-1 px-3 py-2.5 text-[13px] text-ink">{renderValue(v)}</div>
              </div>
            ))}
          </div>
        )}

        <div className="mt-5 flex justify-end">
          <button onClick={onClose} className="btn btn-primary">Close</button>
        </div>
      </div>
    </div>
  );
}
